apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argo
    server: {{ .Values.destinationServer }}
  project: default
  source:
    path: charts/argo-workflows
    repoURL: https://github.com/argoproj/argo-helm
    targetRevision: argo-workflows-0.41.9
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
