apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: {{ .Values.destinationServer }}
  project: default
  source:
    repoURL: https://github.com/istio/istio
    targetRevision: HEAD
    path: manifests/charts/base
