apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appLabel }}
  labels:
    app: {{ .Values.appLabel }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.appLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.appLabel }}
        istio-injection: "true"
    spec:
      serviceAccountName: useless-thing
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: {{ .Values.appLabel }}
        ports:
        - containerPort: {{ .Values.containerPort }}

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: useless-thing
  labels:
    account: {{ .Values.appLabel }}
