apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myapp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http
      number: 8080
      protocol: HTTP
    hosts:
    - lol.app-georgij.com
