apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: myapp-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      name: http
      number: 8080
      protocol: HTTP
    hosts:
    - flask.app-georgij.com
    tls:
      httpsRedirect: true
  - port:
      name: http
      number: 8081
      protocol: HTTP
    hosts:
    - flask.app-georgij.com
    tls:
      httpsRedirect: true
  - port:
      name: https
      number: 8443
      protocol: HTTPS
    hosts:
    - flask.app-georgij.com
    tls:
      mode: SIMPLE
      credentialName: example-com-tls
