apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flask-app
spec:
  hosts:
  - flask.app-georgij.com
  gateways:
  - myapp-gateway
  http:
  - match:
    - headers:
        user-agent:
          exact: guga
      uri:
        exact: /
    route:
    - destination:
        host: flask-app.default.svc.cluster.local
        subset: v1
        port:
          number: 5000
      weight: 90
    - destination:
        host: flask-app.default.svc.cluster.local
        subset: v2
        port:
          number: 5000
      weight: 10

  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: flask-app.default.svc.cluster.local
        subset: v1
        port:
          number: 5000
